logstash:
  host: ${LOGSTASH_HOST:logstash}
  port: ${LOGSTASH_PORT:5000}

management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:zipkin}:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

spring:
  mail:
    host: ${MAIL_HOST:mailhog}
    port: ${MAIL_PORT:1025}
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
  cloud:
    consul:
      host: ${CONSUL_HOST:consul}
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /health
        health-check-interval: 15s
        scheme: http
        port: ${server.port}
        query-passing: true
        register-management-service: false
        deregister-critical-service-after: 90m
