server:
  port: ${SERVICE_PORT:8080}
management:
  server:
    port: ${MANAGEMENT_PORT:9090}
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /
  endpoint:
    health:
      show-details: when-authorized
  info:
    build:
      enabled: true

  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:zipkin}:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{requestId}] - %msg%n'
