{{- if .Values.observability.alertmanager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
type: Opaque
stringData:
  smtp_password: {{ .Values.observability.alertmanager.smtp.password | quote }}
{{- end }}