{{- if .Values.apps.analyticsManager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: analytics-manager-secret
  namespace: {{ .Values.namespaces.mathChallenges }}
  labels:
    app: analytics-manager
type: Opaque
data:
  # --- Auth ---
  AUTH_SECRET: {{ .Values.global.authSecret | b64enc | quote }}

  # --- RabbitMQ Credentials ---
  RABBITMQ_USER: {{ .Values.infrastructure.rabbitmq.user | b64enc | quote }}
  RABBITMQ_PASSWORD: {{ .Values.infrastructure.rabbitmq.password | b64enc | quote }}

  # --- Neo4j Credentials ---
  NEO4J_USER: {{ .Values.infrastructure.neo4jAnalytics.user | b64enc | quote }}
  NEO4J_PASSWORD: {{ .Values.infrastructure.neo4jAnalytics.password | b64enc | quote }}
{{- end }}
