{{- if .Values.apps.challengeManager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: challenge-manager-secret
  labels:
    app: challenge-manager
type: Opaque
data:
  # --- Auth Config ---
  AUTH_SECRET: {{ .Values.global.authSecret | b64enc | quote }}

  # --- Database Credentials ---
  SPRING_DATASOURCE_USERNAME: {{ .Values.infrastructure.postgres.accounts.challengeManager.user | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.infrastructure.postgres.accounts.challengeManager.password | b64enc | quote }}

  # --- RabbitMQ Credentials ---
  RABBITMQ_USER: {{ .Values.infrastructure.rabbitmq.user | b64enc | quote }}
  RABBITMQ_PASSWORD: {{ .Values.infrastructure.rabbitmq.password | b64enc | quote }}

  # --- Redis Credentials ---
  REDIS_USER: {{ .Values.infrastructure.redis.user | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.infrastructure.redis.password | b64enc | quote }}
{{- end }}
