{{- if .Values.observability.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: {{ .Values.observability.grafana.adminUser | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.observability.grafana.adminPassword | quote }}
{{- end }}
