{{- if .Values.infrastructure.neo4jAnalytics.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: neo4j-analytics-secret
  labels:
    app: neo4j-analytics
type: Opaque
data:
  NEO4J_AUTH: {{ printf "%s/%s" .Values.infrastructure.neo4jAnalytics.user .Values.infrastructure.neo4jAnalytics.password | b64enc | quote }}
{{- end }}
