{{- if .Values.apps.notificationManager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: notification-manager-secret
  labels:
    app: notification-manager
type: Opaque
data:
  # Auth secret
  AUTH_SECRET: {{ .Values.global.authSecret | default "default-insecure-secret" | b64enc | quote }}

  # Mail credentials
  MAIL_USERNAME: {{ .Values.apps.notificationManager.mail.username | default "user@mail.com" | b64enc | quote }}
  MAIL_PASSWORD: {{ .Values.apps.notificationManager.mail.password | default "secret" | b64enc | quote }}

  # RabbitMQ credentials
  RABBITMQ_USER: {{ .Values.infrastructure.rabbitmq.user | b64enc | quote }}
  RABBITMQ_PASSWORD: {{ .Values.infrastructure.rabbitmq.password | b64enc | quote }}
{{- end }}
