{{- if .Values.infrastructure.pgadmin.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.infrastructure.pgadmin.email | default "admin@admin.com" | b64enc | quote }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.infrastructure.pgadmin.password | default "admin" | b64enc | quote }}
{{- end }}