{{- if .Values.observability.postgresExporter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
  namespace: {{ .Values.namespaces.observability }}
type: Opaque
stringData:
  DATA_SOURCE_NAME: "postgresql://{{ .Values.infrastructure.postgres.user }}:{{ urlquery .Values.infrastructure.postgres.password }}@{{ .Values.infrastructure.postgres.host }}:{{ .Values.infrastructure.postgres.port }}/postgres?sslmode=disable"
{{- end }}