{{- if .Values.infrastructure.postgres.migrations.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-migrations-secret
type: Opaque
data:
  # Application User Passwords (for migration job)
  POSTGRES_USER_MANAGER_PASSWORD: {{ .Values.infrastructure.postgres.accounts.userManager.password | b64enc | quote }}
  POSTGRES_CHALLENGE_MANAGER_PASSWORD: {{ .Values.infrastructure.postgres.accounts.challengeManager.password | b64enc | quote }}
  POSTGRES_GAMIFICATION_MANAGER_PASSWORD: {{ .Values.infrastructure.postgres.accounts.gamificationManager.password | b64enc | quote }}
{{- end }}
