{{- if .Values.infrastructure.rabbitmq.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: {{ .Values.namespaces.infrastructure }}
  labels:
    app: rabbitmq
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.infrastructure.rabbitmq.user | b64enc | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.infrastructure.rabbitmq.password | b64enc | quote }}
{{- end }}
