{{- if .Values.observability.redisExporter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-exporter-secret
  namespace: {{ .Values.namespaces.observability }}
type: Opaque
stringData:
  REDIS_ADDR: "redis://{{ .Values.infrastructure.redis.host }}:{{ .Values.infrastructure.redis.port }}"
  REDIS_USER: {{ .Values.infrastructure.redis.user | quote }}
  REDIS_PASSWORD: {{ .Values.infrastructure.redis.password | quote }}
{{- end }}