{{- if .Values.infrastructure.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  labels:
    app: redis
type: Opaque
data:
  REDIS_USER: {{ .Values.infrastructure.redis.user | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.infrastructure.redis.password | b64enc | quote }}
{{- end }}
