{{- if .Values.apps.userManager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: user-manager-secret
type: Opaque
data:
  # -- Auth Config --
  AUTH_SECRET: {{ .Values.global.authSecret | b64enc | quote }}

  # -- Spring Data Config --
  SPRING_DATASOURCE_USERNAME: {{ .Values.infrastructure.postgres.accounts.userManager.user | default "user-manager-user" | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.infrastructure.postgres.accounts.userManager.password | default "postgres" | b64enc | quote }}

  # -- Redis Config --
  REDIS_USER: {{ .Values.infrastructure.redis.user | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.infrastructure.redis.password | b64enc | quote }}

  # -- RabbitMQ Config --
  RABBITMQ_USER: {{ .Values.infrastructure.rabbitmq.user | b64enc | quote }}
  RABBITMQ_PASSWORD: {{ .Values.infrastructure.rabbitmq.password | b64enc | quote }}
{{- end }}
