{{- if .Values.infrastructure.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {{ .Values.namespaces.infrastructure }}
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 999
      initContainers:
        - name: fix-permissions
          image: busybox:1.31
          command: ['sh', '-c', 'chown -R 999:999 /data']
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: postgres
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true
          image: postgres:12
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources: {{- toYaml .Values.infrastructure.postgres.resources | nindent 12 }}
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.infrastructure.postgres.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespaces.infrastructure }}
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
{{- end }}