{{- if .Values.infrastructure.rabbitmq.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespaces.infrastructure }}
  labels:
    app: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      securityContext:
        fsGroup: 999
      initContainers:
        - name: fix-permissions
          image: busybox:1.31
          command: ['sh', '-c', 'chown -R 999:999 /data']
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: rabbitmq
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true
          image: rabbitmq:3.13-management
          resources: {{- toYaml .Values.infrastructure.rabbitmq.resources | nindent 12 }}
          ports:
            - containerPort: 5672 # AMQP
            - containerPort: 15672 # Management UI
            - containerPort: 15692 # Prometheus
          envFrom:
            - secretRef:
                name: rabbitmq-secret
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "check_running"]
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "check_port_connectivity"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.infrastructure.rabbitmq.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespaces.infrastructure }}
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
    - name: prometheus
      port: 15692
      targetPort: 15692
  type: ClusterIP
{{- end }}