{{- if .Values.infrastructure.redisinsight.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace: {{ .Values.namespaces.infrastructure }}
  labels:
    app: redisinsight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: redisinsight
          image: {{ .Values.infrastructure.redisinsight.image }}
          resources: {{- toYaml .Values.infrastructure.redisinsight.resources | nindent 12 }}
          ports:
            - containerPort: 5540
---
apiVersion: v1
kind: Service
metadata:
  name: redisinsight
  namespace: {{ .Values.namespaces.infrastructure }}
  labels:
    app: redisinsight
spec:
  selector:
    app: redisinsight
  ports:
    - port: 5540
      targetPort: 5540
  type: ClusterIP
{{- end }}